---
name: build_pkgs_master_on_pytests
description: Build pkgs on circleci once pytests pass
pack: st2ci
enabled: true

trigger:
    type: circle_ci.build_event

criteria:
    trigger.body.payload.branch:
        type: equals
        pattern: master
    trigger.body.payload.vcs_url:
        type: equals
        pattern: "https://github.com/StackStorm/st2"

action:
    ref: st2ci.build_pkgs
    parameters:
        branch: {{trigger.body.payload.branch}}
        revision: {{trigger.body.payload.vcs_revision}}
