---
name: build_pkgs_done
description: Build pkgs on circleci once pytests pass
pack: st2ci
enabled: true

trigger:
    type: circle_ci.build_event

criteria:
    trigger.body.payload.branch:
        type: equals
        pattern: "master"
    trigger.body.payload.vcs_url:
        type: equals
        pattern: "https://github.com/StackStorm/st2-packages"
    trigger.body.payload.build_parameters:
        type: exists
        pattern: ST2_GITREV
    trigger.body.payload.build_parameters.ST2_GITREV:
        type: nequals
        pattern: master

action:
    ref: st2ci.build_pkgs_done
    parameters:
        revision: "{{trigger.body.payload.build_parameters.ST2_GITREV}}"
        status: "{{trigger.body.payload.outcome}}"
        circle_url: "{{trigger.body.payload.build_url}}"
        github_url: "{{trigger.body.payload.build_parameters.GITHUB_URL}}"
        committer: "{{trigger.body.payload.build_parameters.COMMITTER}}"
