---
name: mistral_st2_master
pack: st2ci
description: Run integration tests using Coditation's Mistral fork
enabled: true
trigger:
    type: githubwebhook.github_event
criteria:
    trigger.body.ref:
        pattern: refs/heads/master
        type: equals
    trigger.body.repository.full_name:
        pattern: Coditation/st2
        type: equals
action:
    ref: st2ci.mistral
    parameters: {}
