name: st2_pkg_test_unstable_u14
description: Run package tests on package build
pack: st2ci
enabled: true

trigger:
    type: circle_ci.build_event

criteria:
    trigger.body.payload.branch:
        type: equals
        pattern: master
    trigger.body.payload.vcs_url:
        type: equals
        pattern: "https://github.com/StackStorm/st2-packages"

action:
    ref: st2ci.st2_pkg_e2e_test
    parameters:
        distro: UBUNTU14
        hostname: "st2-pkg-unstable-u14-{{trigger.body.payload.vcs_revision | truncate(10, False, '')}}"
        release: unstable
        triggering_commit_url: "WHO: {{trigger.body.payload.build_parameters.COMMITTER}}, COMPARE: {{trigger.body.payload.build_parameters.GITHUB_URL}}, CIRCLE: {{trigger.body.payload.build_parameters.CIRCLE_URL}}"
        pkg_env: staging
